- hosts: 172.31.35.230
  become: True
  tasks:
    - name: Install apache server
      yum:
       name: httpd
       state: present
    - name: start and enabled
      service: 
        name: httpd
        state: started
        enabled: True
    - name: put html file into server
      copy:
        src: index.html
        dest: /var/www/html/
    - name: change port number
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: '^listen'
        line: 'listen 8080'
      notify:
       - restarted appache
      handlers:  
    - name: restarted
      service: 
         name: httpd
         state: restarted
         enabled: True         
